name: Daily Scrape Banking Data

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        # Install system packages to support Chrome
        sudo apt-get update
        sudo apt-get install -y \
          wget \
          unzip \
          xvfb \
          libnss3 \
          libxss1 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libgbm1 \
          libgtk-3-0

    - name: Run scraper with virtual display (non-headless Chrome)
      run: |
        xvfb-run -a python dailyscraper.py

    - name: Commit scraped CSVs
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add data/
        git commit -m "Auto update scraped data - $(date)" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.TOKEN }}@github.com/cshgoku1/BankDataScraping.git
